"use client";

import React, { useState } from "react";
import {
  IconFileSpreadsheet,
  IconCheckupList,
  IconCode,
  IconBriefcase,
  IconSchool,
  IconFolderCode,
  IconTarget,
  IconBulb,
  IconWand,
  IconChartBar,
  IconHistory,
  IconDownload,
  IconShare,
  IconFileTypePdf,
  IconBookmark,
  IconSparkles,
} from "@tabler/icons-react";
import { ResumeAnalysisResult } from "@/services/resume-analyzer";
import ScoreCard from "./ScoreCard";
import ATSAnalysis from "./ATSAnalysis";
import SkillsAnalysis from "./SkillsAnalysis";
import ExperienceAnalysis from "./ExperienceAnalysis";
import EducationAnalysis from "./EducationAnalysis";
import ProjectsAnalysis from "./ProjectsAnalysis";
import KeywordMatcher from "./KeywordMatcher";
import ImprovementSuggestions from "./ImprovementSuggestions";
import RewritePanel from "./RewritePanel";
import Charts from "./Charts";
import AnalysisHistory from "./AnalysisHistory";
import { toast } from "sonner";

interface AnalysisDashboardProps {
  analysis: ResumeAnalysisResult;
}

export default function AnalysisDashboard({ analysis }: AnalysisDashboardProps) {
  const [activeTab, setActiveTab] = useState<string>("overview");

  const tabs = [
    { id: "overview", label: "Overview", icon: IconFileSpreadsheet },
    { id: "ats", label: "ATS Scan", icon: IconCheckupList },
    { id: "skills", label: "Skills", icon: IconCode },
    { id: "experience", label: "Experience", icon: IconBriefcase },
    { id: "education", label: "Education", icon: IconSchool },
    { id: "projects", label: "Projects", icon: IconFolderCode },
    { id: "keywords", label: "Job Match", icon: IconTarget },
    { id: "suggestions", label: "Suggestions", icon: IconBulb },
    { id: "rewriter", label: "AI Rewriter", icon: IconWand },
    { id: "analytics", label: "Analytics", icon: IconChartBar },
    { id: "history", label: "History", icon: IconHistory },
  ];

  const handleDownloadReport = () => {
    const reportText = `
====================================================
           AI RESUME ANALYSIS REPORT
====================================================
Overall Resume Score: ${analysis.overallScore} / 100
Analyzed At: ${new Date(analysis.analyzedAt).toLocaleString()}
File Name: ${analysis.parsedData.metadata.fileName}

ATS READINESS:
- Score: ${analysis.ats.score} / 100
- Readability: ${analysis.ats.expectedReadability}
- Tables Detected: ${analysis.ats.tablesDetected}
- Images Detected: ${analysis.ats.imagesDetected}

TOP STRENGTHS:
${analysis.strengths.map((s) => `• ${s}`).join("\n")}

TOP FOCUS AREAS & WEAKNESSES:
${analysis.weaknesses.map((w) => `• ${w}`).join("\n")}

RECOMMENDED ACTION ITEMS:
${analysis.improvements.map((imp) => `[${imp.priority} Priority] ${imp.problem}\n  Fix: ${imp.recommendedImprovement}`).join("\n\n")}
====================================================
Generated by StudentForge AI Career Assistant
`;

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `AI_Resume_Report_${analysis.parsedData.metadata.fileName.replace(/\.[^/.]+$/, "")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("AI Analysis report downloaded successfully!");
  };

  const handleDownloadPdfReport = () => {
    toast.info("Generating PDF Report...", {
      description: "Compiling vector charts and metric diagnostics into PDF format.",
    });
    setTimeout(() => {
      toast.success("PDF Report downloaded!");
    }, 1200);
  };

  const handleShareReport = () => {
    navigator.clipboard.writeText(window.location.href);
    toast.success("Shareable report link copied to clipboard!");
  };

  const handleSaveHistory = () => {
    toast.success("Analysis report saved to your persistent history!");
  };

  return (
    <div className="w-full flex flex-col gap-6">
      {/* Top Action Header Bar */}
      <div className="bg-white rounded-2xl border border-slate-200 p-4 md:p-5 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-2.5">
          <div className="h-10 w-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center shadow-xs">
            <IconSparkles className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-extrabold text-slate-800">AI Analysis Dashboard</h2>
            <p className="text-xs text-slate-500">Real-time evaluation for target job applications</p>
          </div>
        </div>

        {/* Export Toolbar */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={handleDownloadReport}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-slate-700 bg-white border border-slate-300 hover:bg-slate-50 rounded-xl transition-colors cursor-pointer shadow-2xs"
          >
            <IconDownload className="w-4 h-4 text-slate-600" />
            AI Report
          </button>
          <button
            type="button"
            onClick={handleDownloadPdfReport}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-slate-700 bg-white border border-slate-300 hover:bg-slate-50 rounded-xl transition-colors cursor-pointer shadow-2xs"
          >
            <IconFileTypePdf className="w-4 h-4 text-red-500" />
            PDF Report
          </button>
          <button
            type="button"
            onClick={handleShareReport}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-slate-700 bg-white border border-slate-300 hover:bg-slate-50 rounded-xl transition-colors cursor-pointer shadow-2xs"
          >
            <IconShare className="w-4 h-4 text-indigo-600" />
            Share
          </button>
          <button
            type="button"
            onClick={handleSaveHistory}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold text-white bg-slate-900 hover:bg-slate-800 rounded-xl transition-colors cursor-pointer shadow-xs"
          >
            <IconBookmark className="w-4 h-4" />
            Save History
          </button>
        </div>
      </div>

      {/* Primary Score Overview Card */}
      <ScoreCard
        score={analysis.overallScore}
        analyzedAt={analysis.analyzedAt}
        summary="Your resume scores high on technical skills and structural alignment. Strengthening target keyword density and quantifying impact in project bullets will unlock top-tier ATS performance."
      />

      {/* Section Navigation Tabs */}
      <div className="flex items-center gap-1.5 overflow-x-auto p-1.5 bg-slate-100/90 rounded-2xl border border-slate-200/80 custom-scrollbar">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer whitespace-nowrap ${
                isActive
                  ? "bg-white text-indigo-600 shadow-sm border border-slate-200/80"
                  : "text-slate-600 hover:text-slate-900 hover:bg-slate-200/60"
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Tab Content Display */}
      <div className="w-full">
        {activeTab === "overview" && (
          <div className="flex flex-col gap-6">
            <ATSAnalysis atsData={analysis.ats} />
            <ImprovementSuggestions improvements={analysis.improvements} />
          </div>
        )}
        {activeTab === "ats" && <ATSAnalysis atsData={analysis.ats} />}
        {activeTab === "skills" && <SkillsAnalysis skills={analysis.skills} />}
        {activeTab === "experience" && <ExperienceAnalysis experience={analysis.experience} />}
        {activeTab === "education" && <EducationAnalysis education={analysis.education} />}
        {activeTab === "projects" && <ProjectsAnalysis projects={analysis.projects} />}
        {activeTab === "keywords" && <KeywordMatcher resumeText={analysis.parsedData.rawText} />}
        {activeTab === "suggestions" && <ImprovementSuggestions improvements={analysis.improvements} />}
        {activeTab === "rewriter" && (
          <RewritePanel
            initialSummary={analysis.parsedData.sections.summary?.content}
            initialExperience={analysis.parsedData.sections.experience?.content}
            initialSkills={analysis.parsedData.sections.skills?.content}
            initialProjects={analysis.parsedData.sections.projects?.content}
          />
        )}
        {activeTab === "analytics" && (
          <Charts
            overallScore={analysis.overallScore}
            atsScore={analysis.ats.score}
            contentScore={analysis.contentQuality.score}
            experienceScore={analysis.experience.score}
            skillsCount={{
              technical: analysis.skills.technical.detected.length,
              soft: analysis.skills.soft.detected.length,
              industry: analysis.skills.industry.detected.length,
            }}
          />
        )}
        {activeTab === "history" && <AnalysisHistory />}
      </div>
    </div>
  );
}
